### ISSUE TITLE
Porting org.apache.commons.math3.distribution

### ISSUE THREAD

**Issue by dantleech** [hoaproject/Math#32]
Would it be interesting to port some or all of the Java Common Math Distribution classes to this library?

- [Java Math](https://commons.apache.org/proper/commons-math/source-repository.html)
- [Source](https://git-wip-us.apache.org/repos/asf?p=commons-math.git;a=tree;f=src/main/java/org/apache/commons/math4/distribution;h=ff862e8a4c4534d5f9d45f40e719427bb4728303;hb=HEAD)

**Comment by Hywan** [comment]
@dantleech Is it used by people?

**Comment by dantleech** [comment]
I have to assume so -- its maintained in Apache Commons and a google search for "Java Statistics" returns this package.

**Comment by Hywan** [comment]
@dantleech Maybe not everything should be ported but we can get some inspiration for sure! Feel free!

**Comment by Hywan** [comment]
ping?

**Comment by Hywan** [comment]
Because #33 has been closed, I assume we can close this one too.
