### ISSUE TITLE
Evaluating multiple formulas with the same variable names

### ISSUE THREAD

**Issue by jesusvallez** [hoaproject/Math#44]
Hello,

I have problems trying to evaluate multiple formulas that uses the same variable names.

When evaluate a set of formulas which have the same variable name I get his exeception:

> Hoa\Math\Exception\AlreadyDefinedConstant: Constant VAR1 is already defined.

but I create an instance every time I do an operation like that:

```
public function evaluateFormula($expression, $variables = array())
{
        $result = null;
        $visitor = new Arithmetic();
        $compiler = Llk::load(new Read('hoa://Library/Math/Arithmetic.pp'));
        
        if (count($variables) > 0) {
            foreach ($variables as $key => $value)
                $visitor->addConstant($key, $value);
            
            try {
                $result = $visitor->visit($compiler->parse($expression));
            } catch (\Exception $e) {
                echo $e->getMessage();
            }
        }
        
        return $result;
    }
}
```

The call 

```
$formservice = new FormulaService();
$result = $formservice->evaluateFormula("VAR1 + VAR2", array(
      "VAR1" => 1,
      "VAR2" => 2));

$this->assertEquals(3, $result);

$formservice = new FormulaService();
$result = $formservice->evaluateFormula("VAR1 + VAR1", array(
      "VAR1" => 1));

$this->assertEquals(2, $result);
```

**Comment by jesusvallez** [comment]
Hello again! 

I solved the problem with the following changes:
- Restoring the context each time I call the Arithmetic with reset = true

> Hoa\Math\Visitor\Arithmetic.php

````
class Arithmetic implements Visitor\Visit
{
    /**
     * Initializes context.
     * @param boolean $reset
     *
     * @return  void
     */
    public function __construct($reset = false)
    {
        $this->initializeContext($reset);
        return;
    }

    protected function initializeContext($reset)
    {
        if (null === $this->_context || $reset) {
            $this->_context = new Math\Context($reset);
        }

        return;
    }
}
````

- Restoring the constants each time I call the Context whit reset = true
> Hoa\Math\Context.php

````
class Context
{
    public function __construct($reset = false)
    {
        $this->initializeConstants($reset);
        $this->initializeFunctions();
        $this->initializeVariables();

        return;
    }

    /**
     * Initialize constants mapping.
     * @param boolean $reset
     *
     * @return void
     */
    protected function initializeConstants($reset = false)
    {
        static $_constants = null;

        if (null === $_constants || $reset) {
            $_constants = new \ArrayObject([
                'PI'      => M_PI,
                'PI_2'    => M_PI_2,
                'PI_4'    => M_PI_4,
                'E'       => M_E,
                'SQRT_PI' => M_SQRTPI,
                'SQRT_2'  => M_SQRT2,
                'SQRT_3'  => M_SQRT3,
                'LN_PI'   => M_LNPI
            ]);
        }

        $this->_constants = $_constants;

        return;
    }
}
````

The call

```
public function evaluateFormula($expression, $variables = array())
{
        $result = null;
        $visitor = new Arithmetic(true);
        $compiler = Llk::load(new Read('hoa://Library/Math/Arithmetic.pp'));
        
        if (count($variables) > 0) {
            foreach ($variables as $clave => $valor)
                $visitor->addConstant($clave, $valor);
            
            try {
                $result = $visitor->visit($compiler->parse($expression));
            } catch (\Exception $e) {
                echo $e->getMessage();
            }
        }
        
        return $result;
    }
}
```

**Comment by jesusvallez** [comment]
@Hywan do you have a better approach for this?

**Comment by Hywan** [comment]
Hello @jesusvallez,

Thanks for using our library!
I notice some issues. First, in `evaluateFormula`, you have `$variables` argument but you use its value as **constants**. This is wrong. You have the `addVariable` method on the `Hoa\Math\Context` object. However, since you are using uppercase for `VAR1` and `VAR2`, you probably mean to use `addConstant` and then change `$variables` for `$constants`.

Second, you are loading the compiler for each call to `evaluateFormula`. Your performance will be horrible :smiley:. I suggest you to have some cache. The simplest one is to use a static variable:
```php
function evaluateFormula(…) {
    static $compiler = null;

    if (null === $compiler) {
        $compiler = Llk::load(new Read('hoa://Library/Math/Arithmetic.pp'));
    }

    …
```

Third, I suggest you to have only one instance of the compiler (as we just did), only one instance of the visitor and several instances of the context. Then, you can set the context to use by the visitor with the `Hoa\Math\Visitor\Arithmetic::setContext` public method. Then you only generate and manipulate a very light object —the `Context`— and re-use all the other “big” objects.

**Comment by jesusvallez** [comment]
Hello @Hywan

Thanks for your reply.
For your first point, yes, It doesnt have a good name, now i call it `$constants`.

Second, I took your suggestion and now my code is faster.

Third, Now I use one context for each formula and It works fine.

Thanks again for your reply

**Comment by Hywan** [comment]
You're welcome!
