### ISSUE TITLE
What is the difference between addConstant and addVariable

### ISSUE THREAD

**Issue by kharysharpe** [hoaproject/Math#47]
Trying to use the library but ran into an unexpected behaviour, hoping you can help.

I expected this to work when I use addConstant, but only works with addVariable.

```php
// 1. Load the compiler.
$compiler = Hoa\Compiler\Llk::load(
    new Hoa\File\Read('hoa://Library/Math/Arithmetic.pp')
);

// 2. Load the visitor, aka the “evaluator”.
$visitor    = new Hoa\Math\Visitor\Arithmetic();

// 3. Declare the expression.
$expression = '(M * X) + C';
    
$visitor->addConstant('M', 2);
$visitor->addConstant('X', 1);
$visitor->addConstant('C', 3);


//$visitor->addVariable('M', function() { return 2; });
//$visitor->addVariable('X', function() { return 1; });
//$visitor->addVariable('C', function() { return 3; });


// 4. Parse the expression.
$ast        = $compiler->parse($expression);

// 5. Evaluate.
var_dump(
    $visitor->visit($ast)
);
```

What is the expected usage of addConstant vs addVariable?

Should there be a check to use the variable and if none found fallback to using the constants otherwise throw an error?

**Comment by Hywan** [comment]
Hello and welcome 😃,

Constants are written in uppercase while variables are writte in lowercase. Also a variable can be overwritten while constants cannot, which is logical.

What is your issue exactly?

**Comment by kharysharpe** [comment]
Thanks for the reply.

Maybe I am doing something wrong but it appears that single letter constants aren't working.

Using the code above says variable M not found. I have to use addVariable as commented in the code.

Great library by the way!!! 
Thanks for building and sharing it.

**Comment by Hywan** [comment]
You're right, this is a limitation.

**Comment by Hywan** [comment]
Since this issue has changed from “question” to “bug”, and this is a “bug”, not an “enhancement”, a new snapshot has been released, https://github.com/hoaproject/Math/releases/tag/1.16.08.29.

Enjoy!

**Comment by kharysharpe** [comment]
Wow that was fast.

Thank you.

I made a class that uses HOA\Math, would appreciate your feedback (and if you like could implement it in your package)

https://gist.github.com/kharysharpe/0f8e9e6d7727a038e19fad8ec1f96c0e

**Comment by Hywan** [comment]
Hey, that's great! Maybe @stephpy or @shouze could provide you a better feedbacks. They did a very similar packages, I don't remember the name though…
